
services:
  app:
    image: programacion
    volumes:
      - ./contenedor/app:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - ./contenedor/app/submissions:/code/submissions  # Añadir esta línea
      - shared-vol:/shared  # Añadir este volumen compartido
    depends_on:
      - bd
    environment:
      DJANGO_KEY: ${DJANGO_KEY}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: bd
      DATABASE_PORT: ${DATABASE_PORT}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
    privileged: true  # Añadir esta línea

  bd:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./contenedor/app/static:/static
      - ./certificados:/certs
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"

  programacion-executor-1:
    build:
      context: ./contenedor
      dockerfile: Dockerfile
    volumes:
      - ./contenedor/app:/code
      - ./contenedor/app/submissions:/code/submissions
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-vol:/shared
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"
    privileged: true

volumes:
  shared-vol:
