# Generated by Django 2.2.28 on 2024-06-01 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0005_ejercicio_descripcion_ejercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='nombre_alumno',
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion_ejercicio',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='RespuestaEjercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=100)),
                ('respuesta', models.TextField()),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.Ejercicio')),
            ],
        ),
    ]
