# Generated by Django 4.2.13 on 2024-06-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0006_auto_20240601_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_maestro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='failedloginattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='respuestaejercicio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
