# Generated by Django 4.2.11 on 2024-06-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0012_ejercicio_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='casos_de_prueba',
            field=models.TextField(default=''),
        ),
    ]
