# Generated by Django 2.2.28 on 2024-06-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0004_auto_20240601_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='descripcion_ejercicio',
            field=models.TextField(default='Descripción del ejercicio'),
        ),
    ]
