# Generated by Django 4.2.11 on 2024-06-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0013_ejercicio_casos_de_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bot_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
